name: FlipBook
description: Flipbook, tu pelicula en papel
url: 'http://flipbook.es'
baseurl: ''
email: tulibro@flipbook.es
twitter: https://twitter.com/flipbookes
youtube: https://www.youtube.com/flipbookes
facebook: https://www.facebook.com/flipbookes
google_analytics: 'UA-00000000-1'

################################################################
################################################################
gems:
  - jekyll-sitemap
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
collections:
  videos:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: videos
    values:
      layout: video